### ISSUE TITLE
Name dirs in config file

### ISSUE THREAD

**Issue by Gbury** [sneeuwballen/benchpress#32]
Similarly to how provers are identified by a name (rather than their command line), it would be useful to be able to name directories. This would allow a few things such as:
- currently the PATH for directories is duplicated, and all occurrences have to be kept in sync, which might annoying
- we could have the same PATH but with different expect status (e.g. one for testing provers, one for testing linters/other non-provers programs)

**Comment by c-cube** [comment]
be able to name a path to refer to it in tasks is good, I think. Same way there is `$cur_dir` already.

For the second item I'd rather have a local update of the config:

```
(with-config
  (dir (path foo) …)
  (task …))
```
so that the directory can be specified only locally.
