### ISSUE TITLE
Unix.Unix_error(Unix.ECONNREFUSED, "connect", "") fails silently

### ISSUE THREAD

**Issue by shonfeder** [sneeuwballen/benchpress#45]
This tool seems very promising! Thanks for making the work available.

I'm trying to get it configured initially. I suspect I'm doing something wrong in the configuration, and I'll keep investigating that, but this behavior seems undesirable regardless, so I figured it merited a report.

When I run benchpress in its currently configured state with default verbosity, I get

```
$ benchpress run -c config.sexp --task test-on-raft
/bin/sh: 1: z3: not found
/bin/sh: 1: cvc4: not found
testing with 1 provers, 0 problems…
OK
STAT:
provers
----------
sat
----------
unsat
----------
sat+unsat
----------
errors
----------
unknown
----------
timeout
----------
memory
----------
total
----------
total_time
ANALYSIS:
provers
----------
improved
----------
ok
----------
disappoint
----------
bad
----------
errors
----------
total
```
 
and a clean exit code. When I pump to max verbosity, I find 

```
[2021-01-26T19:34:15|t0] [info:] run-main.main for paths 
[2021-01-26T19:34:15|t0] [debug:api]
  create client cl_id=0 host="127.0.0.1" port=8090
[2021-01-26T19:34:15|t0] [debug:]
  get-cmd-out "grep -c processor /proc/cpuinfo"
[2021-01-26T19:34:15|t1] [debug:] send progress api to the server
[2021-01-26T19:34:15|t1] [debug:api] make API call task_update
[2021-01-26T19:34:15|t1] [debug:]
  error when trying to connect to API: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[2021-01-26T19:34:15|t0] [debug:] par-map: create pool j=3
[2021-01-26T19:34:15|t0] [debug:] par-map: stop pool
testing with 1 provers, 0 problems…
[2021-01-26T19:34:15|t0] [debug:] par-map: create pool j=1
[2021-01-26T19:34:15|t0] [debug:] par-map: stop pool
[2021-01-26T19:34:15|t0] [info:]
  benchmark done in 0.072s, uuid=dc58297a-da7a-4fc2-bc4a-02f304d739d6
[2021-01-26T19:34:15|t0] [debug:] saving metadata…
[2021-01-26T19:34:15|t0] [debug:] closing db…
OK
STAT:
provers
----------
sat
----------
unsat
----------
sat+unsat
----------
errors
----------
unknown
----------
timeout
----------
memory
----------
total
----------
total_time
ANALYSIS:
provers
----------
improved
----------
ok
----------
disappoint
----------
bad
----------
errors
----------
total
```

So it looks like something in my misconfigured system is causing the connection to be refused. But instead of failing with an error, benchproess is reporting everything to be OK.

This is running on an install pinned to master. My system (although not relevant for the silent error): 

```
Linux system76-pc 5.8.0-7630-generic #32~1609193707~20.04~781bb80~dev-Ubuntu SMP Tue Jan 5 21:22:25 U x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by c-cube** [comment]
Oh, sorry about that. The API thing is a bit misleading and not especially critical. What it means is that `benchpress` (the tool that runs provers, and is ephemeral) tries to contact `benchpress-server` to tell it all about this new task (so that the web API can show the list of active tasks). It's not a fatal error because the web server is not required for actual use, and results will be stored anyway (in some XDG directory, on my machine it's `~/.local/share/benchpress`, as returned by `benchpress dir state`).

**Comment by shonfeder** [comment]
Ah! That makes sense. Thanks :) So if I had `benchpress-server` runing, then I wouldn't have this, presumably! So the lack of any results is due to something totally unrelated. Thank you for explaining!

**Comment by c-cube** [comment]
Yes, that's how it should be. You can try running `benchpress-server` to see if it makes  a distinction (tbh the list of active tasks in the web UI is very, very poorly implemented anyway). A running instance can be found [here](https://benchpress.cedeela.fr/) if you want to see what it looks like.
